sudo pacman -S zsh
sudo pacman -S make
sudo pacman -S cmake
sudo pacman -S gcc
sudo pacman -S clang
sudo pacman -S llvm
sudo pacman -S git
sudo pacman -S wget
sudo pacman -S unzip
sudo pacman -S which
sudo pacman -S curl
sudo pacman -S ninja
sudo pacman -S openssh
sudo pacman -S stow
chsh -s $(which zsh)
