comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true

max_width = 100         # 每行最大宽度
hard_tabs = false       # 是否使用硬制表符
tab_spaces = 2          # Tab 替换为的空格数
use_field_init_shorthand = true # 使用字段初始化简写

use_small_heuristics = "Max"

newline_style = "Unix"
