theme = "tokyonight"

[editor]
line-number = "relative"
mouse = true
auto-pairs = true
true-color = true

[editor.file-picker]
hidden = false  # 显示隐藏文件

[editor.indent-guides]
render = true   # 显示缩进线[keys.normal]
"C-s" = ":w"

[keys.normal]
"C-s" = ":w"   # 在 normal 模式下，Ctrl+S 保存文件

[keys.insert]
"C-s" = ":w"   # 退出插入模式并保存文件

[editor.lsp]
display-progress-messages = true
display-messages = true 
auto-signature-help = true 
display-signature-help-docs = true
snippets = true  
goto-reference-include-declaration = true
enable = true
display-inlay-hints = true  # 显示类型提示

# [editor.indent]
# tab-width = 2
# insert-tab = false

[editor.statusline]
left = ["mode", "spinner"]
right = ["diagnostics", "selections", "position", "file-type"]
