"$schema" = 'https://starship.rs/config-schema.json'
# add_newline = false
# [┌─>](color_blue)
format = """[$os](#6fb424)\
$directory\n
$character\
"""
# [└ ](#6fb424)\

right_format ="""$cmd_duration\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$julia\
$lua\
$python\
$rust\
$battery\
$time"""


# Ubuntu #dd4814
# openSUSE #6fb424


palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 20
style = "fg:bold red "

[[battery.display]]
threshold = 50
style = "fg:bright-yellow "

[[battery.display]]
threshold = 75
style = "fg:bold yellow "

[[battery.display]]
threshold = 85
style = "fg:bright-green "



[jobs]
format = "[$symbols]($style)"
style = "fg:color_yellow bg:color_aqua"

[sudo]
format = "[$symbol ]($style)"
style = "fg:bold bright-purple "
symbol = "⋈┈"
disabled = false

[username]
style_user = "fg:bright-blue "
style_root = "red bold"
format = "[ $user]($style)"
disabled = false
show_always = true

# [hostname]
# ssh_only = false
# format = "<[$hostname]($style)>"
# trim_at = "-"
# style = "bold dimmed white"
# disabled = true

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# threshold = 70
# style = "bold dimmed white"
# disabled = false

[shlvl]
disabled = false
threshold = 1
style = "fg:color_fg0 "
format = "[ $symbol ]($style)"
symbol = "󰅟"
# ↕️

[shell]
disabled = true

[os]
disabled = false
format = " $symbol "
style = "bold yellow"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
openSUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
error_symbol = '[ 󰁕](color_purple)'
success_symbol = "[ 󰁕](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# configure directory
[directory]
# home_symbol = "⌂"
read_only = "◈ "
truncation_length = 20
truncate_to_repo = true
style = "fg:bold cyan "
read_only_style = "fg:bold cyan "
format = '[$read_only]($read_only_style)[ $path]($style)'
repo_root_style = 'bold blue '
repo_root_format = '[$before_root_path]($before_repo_root_style)[  $repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
# style = "bold italic blue"
# format = "[:$path]($style)[$read_only]($read_only_style)"
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Developer" = "󰲋"

# NOTE Git 
# description = "Display symbol for remote Git server"
# [custom.git_server]
# command = """
# GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
# if [[ "$GIT_REMOTE" =~ "github" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "git" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# else
#     GIT_REMOTE_SYMBOL=" " 
# fi
# echo "$GIT_REMOTE_SYMBOL "
# """
# 
# when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
# style = "fg:color_fg0 "
# format = '[ $output ]($style)'


[git_branch]
format = '[\[$symbol$branch\]]($style)'
symbol = " "
style = "fg:bold yellow "

[git_state]
format = '\[[\($state( $progress_current of $progress_total)\)]($style)\]'
[git_commit]
commit_hash_length = 8
style = "fg:bold white "


[git_status]
conflicted = ""
ahead = ""
behind = "󰁕"
diverged = " 󰁕"
untracked = "×${count} "
stashed = ""
modified = "×${count} "
staged = "×${count} "
renamed = "×${count} "
deleted = "×${count} "
style = "bright-blue"
format = '[ $all_status$ahead_behind|]($style)'

# ◪◦ ▴ ▿  ◇ ◌◦ ◃◈ ●◦ ▪ ◎◦ ✕  

[time]
disabled = false
format = "[  $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "bold white"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = '󰅟 '
style = "orange"

# NOTE Language

[cmake]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[nodejs]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[c]
symbol = " "
style = "color_blue"
detect_extensions = ["c", "h", "cc", "cpp", "hpp"]
detect_files = ["makefile", "Makefile", "CMakeLists.txt", "xmake.lua"]
format = "[$symbol($version )]($style) "

[rust]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[golang]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[java]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[lua]
format = " [${symbol}($version )]($style)"
version_format = "${raw}"
symbol = " "
style = "bold bright-yellow"

[kotlin]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[haskell]
symbol = " "
style = "color_blue"
format = "[$symbol($version )]($style) "

[docker_context]
symbol = " "
style = "color_bg3"
format = "[$symbol($version )]($style) "
[julia]
symbol = " "
format = "[$symbol($version )]($style) "

[package]
symbol = "󰏗 "
format = "[$symbol($version )]($style) "

[perl]
symbol = " "
format = "[$symbol($version )]($style) "

[php]
symbol = " "
format = "[$symbol($version )]($style) "

[python]
symbol = " "
#pyenv_version_name = true
format = '[${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
