return {
  AI = require("configs.heirline.components.ai").Ai,
  Vimode = require("configs.heirline.components.vimode").ViMode,
  File = require "configs.heirline.components.file",
  ScrollBar = require "configs.heirline.components.scrollbar",
  LspActive = require "configs.heirline.components.lsprogress",
  Diagnostics = require "configs.heirline.components.diagnose",
  Git = require "configs.heirline.components.git",
  DapMwssages = require "configs.heirline.components.dap",
  WorkDir = require "configs.heirline.components.workdir",
  HelpFilename = require "configs.heirline.components.helpfile",
  TerminalName = require "configs.heirline.components.term",
  Spell = require "configs.heirline.components.spell",
  Overseer = require "configs.heirline.components.overseer",
  BuildSystem = require "configs.heirline.components.winbar_buildsystem",
  Dap = require "configs.heirline.components.winbar_dap",
  CodeCompanion = require "configs.heirline.components.codecompanion",
}
